### ISSUE TITLE
crtdbg.h missing on compile with MinGW

### ISSUE THREAD

**Issue by KoenWindey** [hilch/brwatch#3]
Hi,

When trying to compile in Code Blocks, it throws an error that it can't find crtdbg.h 

A bit of googling tells me that is an issue when compiling with minGW, which is what you suggested. 

I'm only new to this - but, any suggestions?

Perhaps an exe file to save me the hastle? :-)

Thank you
K

**Comment by hilch** [comment]
Hi,
can not not reproduce this (mingw 5.30 /32), but I removed this #include as it was a leftover from Microsoft compiler. Could you test that again, please ? Otherwise use releases ...

**Comment by KoenWindey** [comment]
I will try the release. Tnx.
