### ISSUE TITLE
Other Operating Systems

### ISSUE THREAD

**Issue by RagavL** [hilch/brwatch#4]
I understand it works only on Windows.I have Nvdia nanojetson with ubuntu installed and I am trying to connect to B&R PLC.Can this help?

**Comment by hilch** [comment]
what is your goal ? OpcUA might be a good alternative if you just want to read from and write to PLC variables.
Brwatch relies on PVI which comes for MS Windows only.
But it could work on Linux (x86) with wine. Just try a RUC package installation which containts all necessary dll files as original installer wont work here.

**Comment by RagavL** [comment]
Appreciate your help.I am trying to connect to B&R PLC to extract data and do processing on Nanojetson and based on result send back instruction to PLC

**Comment by hilch** [comment]
hmm then PVI might not be for your project (and brwatch not at all).

alternative 1:
use this open source OPC-UA stack as client: https://open62541.org/ 
I already used it in this project: https://github.com/hilch/control-three-delta-robots

alternative 2:
use own TCP or UDP protocol. B&R server example: https://github.com/hilch/demo-AsTcp-AsUdp

**Comment by RagavL** [comment]
Thanks.How do check if the OPC Server is switched on the B&R Controller PLC?Is there a way to find IP address of the PLC Controller?
