### ISSUE TITLE
Error 13034 

### ISSUE THREAD

**Issue by sunnyinchina** [hilch/brwatch#5]
![64D541D992A7E6CF2778E6D2837C418B](https://user-images.githubusercontent.com/46027205/206429831-0c4b10e4-59cb-434f-947a-dc9a6a465fbe.png)

The error 13034 occurs sometimes，what's its meaning and how to solve it?

**Comment by hilch** [comment]
13034: 'Error in network configuration (parameter SA)'
            '\nUnknown target address (e.g. parameter DA: station number, station name).'
            '\nThere are at least 2 stations with the same station number.'
            '\nSolution: Use a unique station number for the source station.',
            
You might get some additional info by a PVI snapshot from PVI monitor.
